# baseURL = 'http://bartplasmeijer.nl/'
# languageCode = 'en-us'
# title = 'Bart Plasmeijer working on '
# theme = 'archie'

baseURL = "https://bartplasmeijer.nl/"
languageCode = "en-us"
title = "Putting Together"
theme="archie"
copyright = "© Bart Plasmeijer"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="dark" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "My Tech Passion"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/bplasmeijer"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/bartplasmeijer"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

# [[menu.main]]
# name = "About"
# url = "/about"
# weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4